"""create health log tables

Revision ID: 366cec8598e5
Revises: 64f80e7c12d2
Create Date: 2026-05-03 13:39:05.695071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '366cec8598e5'
down_revision: Union[str, None] = '64f80e7c12d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_checkin_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mood_score', sa.Integer(), nullable=True),
    sa.Column('mood_tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_checkin_logs_user_id'), 'daily_checkin_logs', ['user_id'], unique=False)
    op.create_table('meditation_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('meditation_name', sa.String(length=255), nullable=True),
    sa.Column('meditation_type', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meditation_logs_user_id'), 'meditation_logs', ['user_id'], unique=False)
    op.create_table('period_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('flow_intensity', sa.String(length=16), nullable=False),
    sa.Column('pain_level', sa.Integer(), nullable=True),
    sa.Column('clot_presence', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_period_logs_user_id'), 'period_logs', ['user_id'], unique=False)
    op.create_table('sleep_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sleep_hours', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('bed_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wake_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_logs_user_id'), 'sleep_logs', ['user_id'], unique=False)
    op.create_table('water_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_ml', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_logs_user_id'), 'water_logs', ['user_id'], unique=False)

    op.execute("""
        CREATE UNIQUE INDEX uq_daily_checkins_user_date
        ON daily_checkin_logs (user_id, DATE(logged_at AT TIME ZONE 'Asia/Kolkata'));
    """)
    op.execute("""
        CREATE UNIQUE INDEX uq_sleep_logs_user_date
        ON sleep_logs (user_id, DATE(logged_at AT TIME ZONE 'Asia/Kolkata'));
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX uq_sleep_logs_user_date")
    op.execute("DROP INDEX uq_daily_checkins_user_date")

    op.drop_index(op.f('ix_water_logs_user_id'), table_name='water_logs')
    op.drop_table('water_logs')
    op.drop_index(op.f('ix_sleep_logs_user_id'), table_name='sleep_logs')
    op.drop_table('sleep_logs')
    op.drop_index(op.f('ix_period_logs_user_id'), table_name='period_logs')
    op.drop_table('period_logs')
    op.drop_index(op.f('ix_meditation_logs_user_id'), table_name='meditation_logs')
    op.drop_table('meditation_logs')
    op.drop_index(op.f('ix_daily_checkin_logs_user_id'), table_name='daily_checkin_logs')
    op.drop_table('daily_checkin_logs')
    # ### end Alembic commands ###
