"""create health summary log

Revision ID: 502d2f5c2197
Revises: 366cec8598e5
Create Date: 2026-05-03 20:39:56.332063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '502d2f5c2197'
down_revision: Union[str, None] = '366cec8598e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_summaries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('tips', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_summaries_user_id'), 'weekly_summaries', ['user_id'], unique=False)
    op.drop_index('uq_daily_checkins_user_date', table_name='daily_checkin_logs')
    op.drop_index('uq_sleep_logs_user_date', table_name='sleep_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_sleep_logs_user_date', 'sleep_logs', ['user_id', sa.text("date((logged_at AT TIME ZONE 'Asia/Kolkata'::text))")], unique=True)
    op.create_index('uq_daily_checkins_user_date', 'daily_checkin_logs', ['user_id', sa.text("date((logged_at AT TIME ZONE 'Asia/Kolkata'::text))")], unique=True)
    op.drop_index(op.f('ix_weekly_summaries_user_id'), table_name='weekly_summaries')
    op.drop_table('weekly_summaries')
    # ### end Alembic commands ###
