"""add timer and yoga session tables

Revision ID: 66ff23508a6c
Revises: 502d2f5c2197
Create Date: 2026-05-29 09:56:04.838856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ff23508a6c'
down_revision: Union[str, None] = '502d2f5c2197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timer_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('round_count', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timer_sessions_user_id'), 'timer_sessions', ['user_id'], unique=False)
    op.create_table('yoga_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('average_pose_score', sa.Float(), nullable=False),
    sa.Column('calories_estimate', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yoga_sessions_user_id'), 'yoga_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yoga_sessions_user_id'), table_name='yoga_sessions')
    op.drop_table('yoga_sessions')
    op.drop_index(op.f('ix_timer_sessions_user_id'), table_name='timer_sessions')
    op.drop_table('timer_sessions')
    # ### end Alembic commands ###
